services:
  redis:
    image: redis:7-alpine
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - app_network

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    image: anand_id_backend:latest
    container_name: backend
    restart: always
    ports:
      - "4000:4000"
    env_file: .env
    environment:
      REDIS_URL: redis://redis:6379
    depends_on:
      - redis
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  redis_data:
